# Replace with your local server url
@EMS.WebApi_HostAddress = {{HostAddress}}  

GET {{EMS.WebApi_HostAddress}}/api/v2/Employees
Accept: application/json

###

POST {{EMS.WebApi_HostAddress}}/api/v2/employees
Content-Type: application/json

{
  "firstName":"Abhiram",
  "lastName":"AAAAA",
  "email":"Abhiram.p@mail.com",
  "active":true
}

###

GET {{EMS.WebApi_HostAddress}}/api/v2/employees/2
Accept: application/json

###

PUT {{EMS.WebApi_HostAddress}}/api/v2/employees/2
Content-Type: application/json

{
  "id": 2,
  "code":"EMS2",
  "firstName":"Abhiram",
  "lastName":"AAAAAB",
  "email":"Abhiram.p@mail.com",
  "active":true
}

###

DELETE {{EMS.WebApi_HostAddress}}/api/v2/employees/2
Content-Type: application/json

###
